ARG BUILDER_COMPOSER=composer
FROM ${BUILDER_COMPOSER} as composer

FROM nginx:1.15.8-alpine

COPY config/nginx /etc/nginx/conf.d

COPY /web /var/www/web

# Composer installed dependencies and plugins
COPY --from=composer /app/web/app/mu-plugins /var/www/web/app/mu-plugins
COPY --from=composer /app/web/app/plugins /var/www/web/app/plugins
COPY --from=composer /app/web/wp /var/www/web/wp

WORKDIR /var/www/web

EXPOSE 80
